// app/frontend/denguedash/layouts/guest-header.vue
<template>
  <div>
    <header class="bg-blue-800 text-white">
      <nav
        class="container w-5/6 mx-auto flex items-center justify-between py-6"
      >
        <NuxtLink to="/" class="text-2xl font-bold">DengueDash</NuxtLink>
        <ul class="flex space-x-6">
          <li>
            <NuxtLink to="/" class="hover:underline">Dashboard</NuxtLink>
          </li>
          <li>
            <NuxtLink to="/login" class="hover:underline">Login</NuxtLink>
          </li>
        </ul>
      </nav>
    </header>

    <div>
      <slot />
    </div>
  </div>
</template>

// app/frontend/denguedash/app/components/GuestHeader.tsx
import Link from "next/link";

export default function GuestHeader() {
  return (
    <header className="bg-blue-800 text-white">
      <nav className="container w-5/6 mx-auto flex items-center justify-between py-6">
        <Link href="/" className="text-2xl font-bold">
          DengueDash
        </Link>
        <ul className="flex space-x-6">
          <li className="hover:underline">Dashboard</li>
          <li className="hover:underline">Login</li>
        </ul>
      </nav>
    </header>
  );
}
