// app/frontend/denguedash/components/ChoroplethMap.vue
<template>
  <div style="height: 100vh">
    <LMap
      ref="map"
      :zoom="zoom"
      :center="[10.7202, 122.5621]"
      :use-global-leaflet="false"
      :options="mapOptions"
    >
      <LGeoJson
        :geojson="geojson"
        :options-style="geoStyler"
        :options="{
          onEachFeature: (feature, layer) => {
            layer.on({
              mouseover: highlightFeature,
              mouseout: resetHighlight,
              a,
            });
            layer.bindPopup(
              `<b>${feature.properties.shape4}</b><br>${feature.properties.count} cases`
            );
          },
        }"
      />
    </LMap>
  </div>
</template>

<script setup>
import { ref } from "vue";
import geojsonData from "@/assets/geojsons/iloilo_barangays_random.json";

const zoom = ref(13);
const geojson = ref(geojsonData);

const mapOptions = {
  dragging: false,
  touchZoom: false,
  scrollWheelZoom: false,
  doubleClickZoom: false,
  boxZoom: false,
  keyboard: false,
  zoomControl: false,
  // Optionally, disable tap for mobile devices
  tap: false,
};

const geoStyler = (feature) => ({
  color: "white",
  weight: 1,
  fillColor: getColor(feature.properties.count),
  fillOpacity: 0.5,
});

function getColor(d) {
  return d > 150
    ? "#800026"
    : d > 100
      ? "#BD0026"
      : d > 75
        ? "#E31A1C"
        : d > 50
          ? "#FC4E2A"
          : d > 30
            ? "#FD8D3C"
            : d > 20
              ? "#FEB24C"
              : d > 10
                ? "#FED976"
                : "#FFEDA0";
}

function highlightFeature(e) {
  const layer = e.target;

  layer.setStyle({
    color: "grey",
    weight: 2,
    fillOpacity: 0.7,
  });

  layer.bringToFront();
}

function resetHighlight(e) {
  const layer = e.target;

  layer.setStyle({
    color: "white",
    weight: 1,
    fillOpacity: 0.5,
  });
}
</script>

// app/frontend/denguedash/src/components/map/ChoroplethMap.tsx
"use client";

import { MapContainer, GeoJSON } from "react-leaflet";
import { GeoJsonObject } from "geojson";
import { Layer, LeafletEventHandlerFn } from "leaflet";
import geoJsonData from "@assets/geojsons/iloilo_barangays_random.json";
import { BarangayData } from "@/interfaces/map/map.interface";

interface GeoJSONFeature {
  properties: {
    shape4: string;
    count: number;
  };
}

export type ChoroplethMapProps = {
  dengueData: BarangayData[];
};

export default function ChoroplethMap({ dengueData }: ChoroplethMapProps) {
  const geoJson: GeoJsonObject = geoJsonData as GeoJsonObject;

  const getBarangayCaseCount = (barangayName: string): number => {
    const barangayData = dengueData.find(
      (data) => data.barangay === barangayName
    );
    return barangayData ? barangayData.case_count : 0;
  };

  const geoStyler = (feature: GeoJSONFeature | undefined) => {
    if (!feature) return {};
    return {
      color: "white",
      weight: 1,
      fillColor: getColor(getBarangayCaseCount(feature.properties.shape4)),
      fillOpacity: 0.5,
    };
  };

  const getColor = (cases: number): string => {
    return cases > 100
      ? "#800026"
      : cases > 75
        ? "#BD0026"
        : cases > 50
          ? "#E31A1C"
          : cases > 30
            ? "#FC4E2A"
            : cases > 20
              ? "#FD8D3C"
              : cases > 10
                ? "#FEB24C"
                : cases > 5
                  ? "#FED976"
                  : "#FFEDA0";
  };

  const highlightFeature: LeafletEventHandlerFn = (e: any) => {
    const layer = e.target;

    layer.setStyle({
      color: "grey",
      weight: 2,
      fillOpacity: 0.7,
    });

    layer.bringToFront();
  };

  const resetHighlight: LeafletEventHandlerFn = (e: any) => {
    const layer = e.target;

    layer.setStyle({
      color: "white",
      weight: 1,
      fillOpacity: 0.5,
    });
  };

  const mapOnEachFeature = (feature: GeoJSONFeature, layer: Layer) => {
    layer.on({
      mouseover: highlightFeature,
      mouseout: resetHighlight,
    });

    layer.bindPopup(
      `<b>${feature.properties.shape4}</b><br>${getBarangayCaseCount(feature.properties.shape4)} cases`
    );
  };

  const ILOILO_CITY_COORDS: [number, number] = [10.73, 122.5521];
  const ZOOM_LEVEL: number = 13;

  return (
    <MapContainer
      style={{ height: "80vh" }}
      zoom={ZOOM_LEVEL}
      center={ILOILO_CITY_COORDS}
      dragging={false}
      touchZoom={false}
      scrollWheelZoom={false}
      doubleClickZoom={false}
      boxZoom={false}
      keyboard={false}
      zoomControl={false}
    >
      <GeoJSON
        key={JSON.stringify(dengueData)}
        data={geoJson}
        style={geoStyler}
        onEachFeature={mapOnEachFeature}
      />
    </MapContainer>
  );
}
